export const EN = {
  welcomeSubtitle: 'Identify more than 3000+ plants and\n88% accuracy.',
  privacyPolicy: ' By tapping next, you are agreeing to PlantID',
  privacyPolicyCont: 'Terms of Use & Privacy Policy.',
  getStarted: 'Get Started',
  welcometo: 'Welcome to PlantApp',
  hiPlant: 'Hi,plant lover !',
  goodAfternoon: 'Good Afternoon!🌤️',
  oneMonth: '1 Month',
  autoRenewable: '$2.99/month, auto renewable',
  oneYear: '1 Year',
  firstThreeDays: 'First 3 days free, then $529,99/year',
  tryFree: 'Try free for 3 days',
  accessAll: 'Access All Features',
  premium: 'Premium',
  afterThreeDays:
    'After the 3-day free trial period you’ll be charged ₺274.99 per year unless you\ncancel before the trial expires. Yearly Subscription is Auto-Renewable',
  tPR: 'Terms  •  Privacy  •  Restore',
  unlimited: 'Unlimited',
  plantIdentify: 'Plant Identify',
  faster: 'Faster',
  process: 'Process',
  Detailed: 'Detailed',
  plantCare: 'Plant care',
  continue: 'Continue',
  takeAPhoto: 'Take a photo to identify\nthe plant!',
  getPlant: 'Get plant care guides',
};
